import { useState } from "react";
import { FileText, ChevronDown, ChevronUp, ExternalLink } from "lucide-react";

interface WebhookReportViewerProps {
  reportText: string;
  sessionId: string;
}

export default function WebhookReportViewer({ reportText, sessionId }: WebhookReportViewerProps) {
  const [expanded, setExpanded] = useState(true);

  // Parse sections from the report text
  const sections = reportText.split(/\n(?=[A-Z][A-Za-z\s/()]+\n)/).filter(Boolean);

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-5 w-5" style={{ color: "#A78BFA" }} />
          <h3 className="font-extrabold" style={{ color: "#2D1B69" }}>
            Make.com Analysis Report
          </h3>
        </div>
        <button
          className="lila-btn-secondary text-xs flex items-center gap-1"
          onClick={() => setExpanded(!expanded)}
        >
          {expanded ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
          {expanded ? "Collapse" : "Expand"}
        </button>
      </div>

      {expanded && (
        <div
          className="rounded-2xl p-5 space-y-4 text-sm leading-relaxed max-h-[600px] overflow-y-auto"
          style={{
            background: "linear-gradient(135deg, #FAFAFE 0%, #F5F3FF 100%)",
            border: "1.5px solid #EDE9FF",
            color: "#2D1B69",
          }}
        >
          {/* Render the report with basic formatting */}
          {reportText.split("\n").map((line, i) => {
            const trimmed = line.trim();
            if (!trimmed) return <div key={i} className="h-2" />;

            // Section headers (lines that are all caps or title-like)
            if (
              /^[A-Z][A-Za-z\s/()–—-]+$/.test(trimmed) &&
              trimmed.length < 80 &&
              !trimmed.startsWith("-")
            ) {
              return (
                <h4 key={i} className="font-bold text-sm pt-2" style={{ color: "#7C3AED" }}>
                  {trimmed}
                </h4>
              );
            }

            // Bullet points
            if (trimmed.startsWith("- ")) {
              return (
                <div key={i} className="flex gap-2 pl-2">
                  <span style={{ color: "#A78BFA" }}>•</span>
                  <span style={{ color: "#2D1B69" }}>{trimmed.slice(2)}</span>
                </div>
              );
            }

            // Bold markers like **text**
            const formatted = trimmed.replace(
              /\*\*(.+?)\*\*/g,
              '<strong style="color:#7C3AED">$1</strong>'
            );

            return (
              <p
                key={i}
                style={{ color: "#2D1B69" }}
                dangerouslySetInnerHTML={{ __html: formatted }}
              />
            );
          })}
        </div>
      )}

      <p className="text-xs italic" style={{ color: "#A89DC4" }}>
        This report was generated by your Make.com workflow and saved for this session. It can be accessed anytime from the session summary.
      </p>
    </div>
  );
}
